/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SecureUnionID {
  public static void HASHIT(String hashstring, String m) {
    SecureUnionIDJNI.HASHIT(hashstring, m);
  }

  public static long randomSeed() {
    return SecureUnionIDJNI.randomSeed();
  }

  public static int MasterKeygen(long ran, byte[] BYTE) {
    return SecureUnionIDJNI.MasterKeygen(ran, BYTE);
  }

  public static int Keygen(byte[] arg0, String dspid, byte[] arg2, byte[] arg3, byte[] arg4) {
    return SecureUnionIDJNI.Keygen(arg0, dspid, arg2, arg3, arg4);
  }

  public static int System_Keygen(String[] arg0, String[] arg1, int numofmedia, byte[] arg3, byte[] arg4) {
    return SecureUnionIDJNI.System_Keygen(arg0, arg1, numofmedia, arg3, arg4);
  }

  public static int Blinding(String did, long seed, byte[] arg2, byte[] arg3) {
    return SecureUnionIDJNI.Blinding(did, seed, arg2, arg3);
  }

  public static int Enc(byte[] arg0, byte[] arg1, byte[] arg2) {
    return SecureUnionIDJNI.Enc(arg0, arg1, arg2);
  }

  public static int Unblinding(String[] STRING_ARRAY, int numofmedia, byte[] arg2, byte[] arg3, byte[] arg4) {
    return SecureUnionIDJNI.Unblinding(STRING_ARRAY, numofmedia, arg2, arg3, arg4);
  }

  public static int verify_individual(String[] arg0, String[] arg1, String[] arg2, String did, int numofmedia, byte[] BYTE) {
    return SecureUnionIDJNI.verify_individual(arg0, arg1, arg2, did, numofmedia, BYTE);
  }

  public static int batch_verify(String[] arg0, String[] arg1, byte[] BYTE, int numofdid) {
    return SecureUnionIDJNI.batch_verify(arg0, arg1, BYTE, numofdid);
  }

}
